/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type RefundValidationErrorData = {
  amount?: string | undefined;
  /**
   * Used for generic errors when invalid request data isn't attributed to a single request field.
   */
  error?: string | undefined;
};

export class RefundValidationError extends Error {
  amount?: string | undefined;
  /**
   * Used for generic errors when invalid request data isn't attributed to a single request field.
   */
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: RefundValidationErrorData;

  constructor(err: RefundValidationErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.amount != null) this.amount = err.amount;
    if (err.error != null) this.error = err.error;

    this.name = "RefundValidationError";
  }
}

/** @internal */
export const RefundValidationError$inboundSchema: z.ZodType<
  RefundValidationError,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: z.string().optional(),
  error: z.string().optional(),
})
  .transform((v) => {
    return new RefundValidationError(v);
  });

/** @internal */
export type RefundValidationError$Outbound = {
  amount?: string | undefined;
  error?: string | undefined;
};

/** @internal */
export const RefundValidationError$outboundSchema: z.ZodType<
  RefundValidationError$Outbound,
  z.ZodTypeDef,
  RefundValidationError
> = z.instanceof(RefundValidationError)
  .transform(v => v.data$)
  .pipe(z.object({
    amount: z.string().optional(),
    error: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RefundValidationError$ {
  /** @deprecated use `RefundValidationError$inboundSchema` instead. */
  export const inboundSchema = RefundValidationError$inboundSchema;
  /** @deprecated use `RefundValidationError$outboundSchema` instead. */
  export const outboundSchema = RefundValidationError$outboundSchema;
  /** @deprecated use `RefundValidationError$Outbound` instead. */
  export type Outbound = RefundValidationError$Outbound;
}
