// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

type AccountTerminalApplicationError struct {
	TerminalApplicationID *string                 `json:"terminalApplicationID,omitempty"`
	HTTPMeta              components.HTTPMetadata `json:"-"`
}

var _ error = &AccountTerminalApplicationError{}

func (e *AccountTerminalApplicationError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
