// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

type ScheduleValidationError struct {
	Occurrences map[string]string       `json:"occurrences,omitempty"`
	Recur       *string                 `json:"recur,omitempty"`
	Description *string                 `json:"description,omitempty"`
	HTTPMeta    components.HTTPMetadata `json:"-"`
}

var _ error = &ScheduleValidationError{}

func (e *ScheduleValidationError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
