/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { bankAccountsCreateAttestation } from "../../funcs/bankAccountsCreateAttestation.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateBankAccountAttestationRequest$inboundSchema,
};

export const tool$bankAccountsCreateAttestation: ToolDefinition<typeof args> = {
  name: "bank-accounts-create-attestation",
  description:
    `  Submit a new authorization attestation for a bank account in an \`errored\` status due to an R29 ACH return (\`Corporate Customer Advises Not Authorized\`).

  After obtaining new authorization from the receiver, submit an attestation with the date the authorization was obtained and a brief description of how the authorization was obtained. If the attestation is accepted, the bank account transitions from \`errored\` to \`verified\`.

  Constraints

  - The bank account's current errored status must be the result of an R29 return.
  - \`attestedAt\` must be on or after the date of the bank account's most recent R29 return and cannot be a future date.
  - Only one attestation may be submitted for a bank account. Use the [Get attestation eligibility](https://docs.moov.io/api/sources/bank-accounts/attestation-eligibility/) endpoint to confirm eligibility before submitting an attestation.

  This endpoint is available only to allowlisted partners. Contact Moov Support for more information.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await bankAccountsCreateAttestation(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
