/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountTerminalApplicationsGet } from "../funcs/accountTerminalApplicationsGet.js";
import { accountTerminalApplicationsGetConfiguration } from "../funcs/accountTerminalApplicationsGetConfiguration.js";
import { accountTerminalApplicationsLink } from "../funcs/accountTerminalApplicationsLink.js";
import { accountTerminalApplicationsList } from "../funcs/accountTerminalApplicationsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class AccountTerminalApplications extends ClientSDK {
  /**
   * Link an account with a terminal application.
   *
   * To access this endpoint using an [access token](https://docs.moov.io/api/authentication/access-tokens/)
   * you'll need to specify the `/accounts/{accountID}/terminal-applications.write` scope.
   */
  async link(
    request: operations.LinkAccountTerminalApplicationRequest,
    options?: RequestOptions,
  ): Promise<operations.LinkAccountTerminalApplicationResponse> {
    return unwrapAsync(accountTerminalApplicationsLink(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve all terminal applications linked to a specific account.
   *
   * To access this endpoint using an [access token](https://docs.moov.io/api/authentication/access-tokens/)
   * you'll need to specify the `/accounts/{accountID}/terminal-applications.read` scope.
   */
  async list(
    request: operations.ListAccountTerminalApplicationsRequest,
    options?: RequestOptions,
  ): Promise<operations.ListAccountTerminalApplicationsResponse> {
    return unwrapAsync(accountTerminalApplicationsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Verifies if a specific Terminal Application is linked to an Account. This endpoint acts as a validation check for the link's existence.
   *
   * To access this endpoint using an [access token](https://docs.moov.io/api/authentication/access-tokens/)
   * you'll need to specify the `/accounts/{accountID}/terminal-applications.read` scope.
   */
  async get(
    request: operations.GetAccountTerminalApplicationRequest,
    options?: RequestOptions,
  ): Promise<operations.GetAccountTerminalApplicationResponse> {
    return unwrapAsync(accountTerminalApplicationsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Fetch the configuration for a given Terminal Application linked to a specific Account.
   *
   * To access this endpoint using an [access token](https://docs.moov.io/api/authentication/access-tokens/)
   * you'll need to specify the `/accounts/{accountID}/terminal-configuration.read` scope.
   */
  async getConfiguration(
    request: operations.GetTerminalConfigurationRequest,
    options?: RequestOptions,
  ): Promise<operations.GetTerminalConfigurationResponse> {
    return unwrapAsync(accountTerminalApplicationsGetConfiguration(
      this,
      request,
      options,
    ));
  }
}
