/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { cardIssuingGet } from "../funcs/cardIssuingGet.js";
import { cardIssuingGetFull } from "../funcs/cardIssuingGetFull.js";
import { cardIssuingList } from "../funcs/cardIssuingList.js";
import { cardIssuingRequest } from "../funcs/cardIssuingRequest.js";
import { cardIssuingUpdate } from "../funcs/cardIssuingUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class CardIssuing extends ClientSDK {
  /**
   * Request a virtual card be issued.
   *
   * To access this endpoint using an [access token](https://docs.moov.io/api/authentication/access-tokens/)
   * you'll need to specify the `/accounts/{accountID}/issued-cards.write` scope.
   */
  async request(
    request: operations.RequestCardRequest,
    options?: RequestOptions,
  ): Promise<operations.RequestCardResponse> {
    return unwrapAsync(cardIssuingRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * List Moov issued cards existing for the account.
   *
   * To access this endpoint using an [access token](https://docs.moov.io/api/authentication/access-tokens/)
   * you'll need to specify the `/accounts/{accountID}/issued-cards.read` scope.
   */
  async list(
    request: operations.ListIssuedCardsRequest,
    options?: RequestOptions,
  ): Promise<operations.ListIssuedCardsResponse> {
    return unwrapAsync(cardIssuingList(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a single issued card associated with a Moov account.
   *
   * To access this endpoint using an [access token](https://docs.moov.io/api/authentication/access-tokens/)
   * you'll need to specify the `/accounts/{accountID}/issued-cards.read` scope.
   */
  async get(
    request: operations.GetIssuedCardRequest,
    options?: RequestOptions,
  ): Promise<operations.GetIssuedCardResponse> {
    return unwrapAsync(cardIssuingGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a Moov issued card.
   *
   * To access this endpoint using an [access token](https://docs.moov.io/api/authentication/access-tokens/)
   * you'll need to specify the `/accounts/{accountID}/issued-cards.write` scope.
   */
  async update(
    request: operations.UpdateIssuedCardRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateIssuedCardResponse | undefined> {
    return unwrapAsync(cardIssuingUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get issued card with PAN, CVV, and expiration.
   *
   * Only use this endpoint if you have provided Moov with a copy of your PCI attestation of compliance.
   *
   * To access this endpoint using an [access token](https://docs.moov.io/api/authentication/access-tokens/)
   * you'll need to specify the `/accounts/{accountID}/issued-cards.read-secure` scope.
   */
  async getFull(
    request: operations.GetFullIssuedCardRequest,
    options?: RequestOptions,
  ): Promise<operations.GetFullIssuedCardResponse> {
    return unwrapAsync(cardIssuingGetFull(
      this,
      request,
      options,
    ));
  }
}
