/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { googlePayLinkToken } from "../funcs/googlePayLinkToken.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class GooglePay extends ClientSDK {
  /**
   * Connect a Google Pay token to the specified account.
   *
   * The `token` data is defined by Google Pay and should be passed through from Google Pay's response unmodified.
   *
   * To access this endpoint using an [access token](https://docs.moov.io/api/authentication/access-tokens/)
   * you'll need to specify the `/accounts/{accountID}/cards.write` scope.
   */
  async linkToken(
    request: operations.LinkGooglePayTokenRequest,
    options?: RequestOptions,
  ): Promise<operations.LinkGooglePayTokenResponse> {
    return unwrapAsync(googlePayLinkToken(
      this,
      request,
      options,
    ));
  }
}
