/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { industriesListIndustries } from "../funcs/industriesListIndustries.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Industries extends ClientSDK {
  /**
   *   Returns a list of all industry titles and their corresponding MCC/SIC/NAICS codes. Results are ordered by title.
   *
   *   To use this endpoint from the browser, you'll need to specify the `/profile-enrichment.read` scope when generating a [token](https://docs.moov.io/api/authentication/access-tokens/).
   */
  async listIndustries(
    security: operations.ListIndustriesSecurity,
    request: operations.ListIndustriesRequest,
    options?: RequestOptions,
  ): Promise<Array<components.EnrichedIndustry>> {
    return unwrapAsync(industriesListIndustries(
      this,
      security,
      request,
      options,
    ));
  }
}
