/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymentMethodsGetPaymentMethod } from "../funcs/paymentMethodsGetPaymentMethod.js";
import { paymentMethodsListPaymentMethods } from "../funcs/paymentMethodsListPaymentMethods.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class PaymentMethods extends ClientSDK {
  /**
   * Retrieve a list of payment methods associated with a Moov account. Read our [payment methods guide](https://docs.moov.io/guides/money-movement/payment-methods/) to learn more.
   *
   * To use this endpoint from the browser, you'll need to specify the `/accounts/{accountID}/payment-methods.read` scope when generating a [token](https://docs.moov.io/api/authentication/access-tokens/).
   */
  async listPaymentMethods(
    security: operations.ListPaymentMethodsSecurity,
    request: operations.ListPaymentMethodsRequest,
    options?: RequestOptions,
  ): Promise<Array<components.PaymentMethod>> {
    return unwrapAsync(paymentMethodsListPaymentMethods(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get the specified payment method associated with a Moov account. Read our [payment methods guide](https://docs.moov.io/guides/money-movement/payment-methods/) to learn more.
   *
   * To use this endpoint from the browser, you'll need to specify the `/accounts/{accountID}/payment-methods.read` scope when generating a [token](https://docs.moov.io/api/authentication/access-tokens/).
   */
  async getPaymentMethod(
    security: operations.GetPaymentMethodSecurity,
    request: operations.GetPaymentMethodRequest,
    options?: RequestOptions,
  ): Promise<components.PaymentMethod> {
    return unwrapAsync(paymentMethodsGetPaymentMethod(
      this,
      security,
      request,
      options,
    ));
  }
}
