/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pingPing } from "../funcs/pingPing.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Ping extends ClientSDK {
  /**
   * A simple endpoint to check auth.
   *
   * To access this endpoint using an [access token](https://docs.moov.io/api/authentication/access-tokens/)
   * you'll need to specify the `/ping.read` scope.
   */
  async ping(
    request: operations.PingRequest,
    options?: RequestOptions,
  ): Promise<operations.PingResponse | undefined> {
    return unwrapAsync(pingPing(
      this,
      request,
      options,
    ));
  }
}
