workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    latest:
        inputs:
            - location: registry.speakeasyapi.dev/moov/moov/api-v2025.04.00
        registry:
            location: registry.speakeasyapi.dev/moov/moov/typescript-v2025.04.00
targets:
    latest:
        target: typescript
        source: latest
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/moov/moov/v2025.04.00-ts-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
