workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    latest:
        inputs:
            - location: registry.speakeasyapi.dev/moov/moov/api-latest
        overlays:
            - location: ./.speakeasy/transfer-discriminators-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/latest
targets:
    moov:
        target: typescript
        source: latest
        publish:
            npm:
                token: $npm_token
