/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateTerminalApplicationResponse = {
  headers: { [k: string]: Array<string> };
  result: components.TerminalApplication;
};

/** @internal */
export const CreateTerminalApplicationResponse$inboundSchema: z.ZodType<
  CreateTerminalApplicationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: components.TerminalApplication$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type CreateTerminalApplicationResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.TerminalApplication$Outbound;
};

/** @internal */
export const CreateTerminalApplicationResponse$outboundSchema: z.ZodType<
  CreateTerminalApplicationResponse$Outbound,
  z.ZodTypeDef,
  CreateTerminalApplicationResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.TerminalApplication$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function createTerminalApplicationResponseToJSON(
  createTerminalApplicationResponse: CreateTerminalApplicationResponse,
): string {
  return JSON.stringify(
    CreateTerminalApplicationResponse$outboundSchema.parse(
      createTerminalApplicationResponse,
    ),
  );
}
export function createTerminalApplicationResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateTerminalApplicationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateTerminalApplicationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateTerminalApplicationResponse' from JSON`,
  );
}
