/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateDepositAccountRequest = {
  accountID: string;
  /**
   * Identifies the core banking source system that produced the request body.
   */
  xSourceSystem: components.SourceSystem;
  requestBody: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type CreateDepositAccountResponse = {
  headers: { [k: string]: Array<string> };
  result: components.DepositAccountIngestedResponse;
};

/** @internal */
export const CreateDepositAccountRequest$inboundSchema: z.ZodType<
  CreateDepositAccountRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  accountID: types.string(),
  "X-Source-System": components.SourceSystem$inboundSchema,
  RequestBody: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
}).transform((v) => {
  return remap$(v, {
    "X-Source-System": "xSourceSystem",
    "RequestBody": "requestBody",
  });
});
/** @internal */
export type CreateDepositAccountRequest$Outbound = {
  accountID: string;
  "X-Source-System": string;
  RequestBody: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const CreateDepositAccountRequest$outboundSchema: z.ZodType<
  CreateDepositAccountRequest$Outbound,
  z.ZodTypeDef,
  CreateDepositAccountRequest
> = z.object({
  accountID: z.string(),
  xSourceSystem: components.SourceSystem$outboundSchema,
  requestBody: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
}).transform((v) => {
  return remap$(v, {
    xSourceSystem: "X-Source-System",
    requestBody: "RequestBody",
  });
});

export function createDepositAccountRequestToJSON(
  createDepositAccountRequest: CreateDepositAccountRequest,
): string {
  return JSON.stringify(
    CreateDepositAccountRequest$outboundSchema.parse(
      createDepositAccountRequest,
    ),
  );
}
export function createDepositAccountRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateDepositAccountRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateDepositAccountRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateDepositAccountRequest' from JSON`,
  );
}

/** @internal */
export const CreateDepositAccountResponse$inboundSchema: z.ZodType<
  CreateDepositAccountResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: components.DepositAccountIngestedResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type CreateDepositAccountResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.DepositAccountIngestedResponse$Outbound;
};

/** @internal */
export const CreateDepositAccountResponse$outboundSchema: z.ZodType<
  CreateDepositAccountResponse$Outbound,
  z.ZodTypeDef,
  CreateDepositAccountResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.DepositAccountIngestedResponse$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function createDepositAccountResponseToJSON(
  createDepositAccountResponse: CreateDepositAccountResponse,
): string {
  return JSON.stringify(
    CreateDepositAccountResponse$outboundSchema.parse(
      createDepositAccountResponse,
    ),
  );
}
export function createDepositAccountResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateDepositAccountResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateDepositAccountResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateDepositAccountResponse' from JSON`,
  );
}
