/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetMerchantProcessingAgreementRequest = {
  accountID: string;
};

export type GetMerchantProcessingAgreementResponse = {
  headers: { [k: string]: Array<string> };
  result: ReadableStream<Uint8Array>;
};

/** @internal */
export const GetMerchantProcessingAgreementRequest$inboundSchema: z.ZodType<
  GetMerchantProcessingAgreementRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  accountID: z.string(),
});
/** @internal */
export type GetMerchantProcessingAgreementRequest$Outbound = {
  accountID: string;
};

/** @internal */
export const GetMerchantProcessingAgreementRequest$outboundSchema: z.ZodType<
  GetMerchantProcessingAgreementRequest$Outbound,
  z.ZodTypeDef,
  GetMerchantProcessingAgreementRequest
> = z.object({
  accountID: z.string(),
});

export function getMerchantProcessingAgreementRequestToJSON(
  getMerchantProcessingAgreementRequest: GetMerchantProcessingAgreementRequest,
): string {
  return JSON.stringify(
    GetMerchantProcessingAgreementRequest$outboundSchema.parse(
      getMerchantProcessingAgreementRequest,
    ),
  );
}
export function getMerchantProcessingAgreementRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetMerchantProcessingAgreementRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetMerchantProcessingAgreementRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetMerchantProcessingAgreementRequest' from JSON`,
  );
}

/** @internal */
export const GetMerchantProcessingAgreementResponse$inboundSchema: z.ZodType<
  GetMerchantProcessingAgreementResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.instanceof(ReadableStream<Uint8Array>),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type GetMerchantProcessingAgreementResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: ReadableStream<Uint8Array>;
};

/** @internal */
export const GetMerchantProcessingAgreementResponse$outboundSchema: z.ZodType<
  GetMerchantProcessingAgreementResponse$Outbound,
  z.ZodTypeDef,
  GetMerchantProcessingAgreementResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.instanceof(ReadableStream<Uint8Array>),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function getMerchantProcessingAgreementResponseToJSON(
  getMerchantProcessingAgreementResponse:
    GetMerchantProcessingAgreementResponse,
): string {
  return JSON.stringify(
    GetMerchantProcessingAgreementResponse$outboundSchema.parse(
      getMerchantProcessingAgreementResponse,
    ),
  );
}
export function getMerchantProcessingAgreementResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetMerchantProcessingAgreementResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetMerchantProcessingAgreementResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetMerchantProcessingAgreementResponse' from JSON`,
  );
}
