/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListProductCategoriesResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ProductCategories;
};

/** @internal */
export const ListProductCategoriesResponse$inboundSchema: z.ZodType<
  ListProductCategoriesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: components.ProductCategories$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type ListProductCategoriesResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.ProductCategories$Outbound;
};

/** @internal */
export const ListProductCategoriesResponse$outboundSchema: z.ZodType<
  ListProductCategoriesResponse$Outbound,
  z.ZodTypeDef,
  ListProductCategoriesResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.ProductCategories$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function listProductCategoriesResponseToJSON(
  listProductCategoriesResponse: ListProductCategoriesResponse,
): string {
  return JSON.stringify(
    ListProductCategoriesResponse$outboundSchema.parse(
      listProductCategoriesResponse,
    ),
  );
}
export function listProductCategoriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListProductCategoriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListProductCategoriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListProductCategoriesResponse' from JSON`,
  );
}
