/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MarkPaidInvoiceGlobals = {
  /**
   * Specify an API version.
   *
   * @remarks
   *
   * API versioning follows the format `vYYYY.QQ.BB`, where
   *   - `YYYY` is the year
   *   - `QQ` is the two-digit month for the first month of the quarter (e.g., 01, 04, 07, 10)
   *   - `BB` is the build number, starting at `.01`, for subsequent builds in the same quarter.
   *     - For example, `v2024.01.00` is the initial release of the first quarter of 2024.
   *
   * The `latest` version represents the most recent development state. It may include breaking changes and should be treated as a beta release.
   * When no version is specified, the API defaults to `v2024.01.00`.
   */
  xMoovVersion?: string | undefined;
};

export type MarkPaidInvoiceRequest = {
  accountID: string;
  invoiceID: string;
  markInvoicePaid: components.MarkInvoicePaid;
};

export type MarkPaidInvoiceResponse = {
  headers: { [k: string]: Array<string> };
  result: components.Invoice;
};

/** @internal */
export const MarkPaidInvoiceGlobals$inboundSchema: z.ZodType<
  MarkPaidInvoiceGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Moov-Version": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "X-Moov-Version": "xMoovVersion",
  });
});
/** @internal */
export type MarkPaidInvoiceGlobals$Outbound = {
  "X-Moov-Version"?: string | undefined;
};

/** @internal */
export const MarkPaidInvoiceGlobals$outboundSchema: z.ZodType<
  MarkPaidInvoiceGlobals$Outbound,
  z.ZodTypeDef,
  MarkPaidInvoiceGlobals
> = z.object({
  xMoovVersion: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    xMoovVersion: "X-Moov-Version",
  });
});

export function markPaidInvoiceGlobalsToJSON(
  markPaidInvoiceGlobals: MarkPaidInvoiceGlobals,
): string {
  return JSON.stringify(
    MarkPaidInvoiceGlobals$outboundSchema.parse(markPaidInvoiceGlobals),
  );
}
export function markPaidInvoiceGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<MarkPaidInvoiceGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MarkPaidInvoiceGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MarkPaidInvoiceGlobals' from JSON`,
  );
}

/** @internal */
export const MarkPaidInvoiceRequest$inboundSchema: z.ZodType<
  MarkPaidInvoiceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  accountID: z.string(),
  invoiceID: z.string(),
  MarkInvoicePaid: components.MarkInvoicePaid$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "MarkInvoicePaid": "markInvoicePaid",
  });
});
/** @internal */
export type MarkPaidInvoiceRequest$Outbound = {
  accountID: string;
  invoiceID: string;
  MarkInvoicePaid: components.MarkInvoicePaid$Outbound;
};

/** @internal */
export const MarkPaidInvoiceRequest$outboundSchema: z.ZodType<
  MarkPaidInvoiceRequest$Outbound,
  z.ZodTypeDef,
  MarkPaidInvoiceRequest
> = z.object({
  accountID: z.string(),
  invoiceID: z.string(),
  markInvoicePaid: components.MarkInvoicePaid$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    markInvoicePaid: "MarkInvoicePaid",
  });
});

export function markPaidInvoiceRequestToJSON(
  markPaidInvoiceRequest: MarkPaidInvoiceRequest,
): string {
  return JSON.stringify(
    MarkPaidInvoiceRequest$outboundSchema.parse(markPaidInvoiceRequest),
  );
}
export function markPaidInvoiceRequestFromJSON(
  jsonString: string,
): SafeParseResult<MarkPaidInvoiceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MarkPaidInvoiceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MarkPaidInvoiceRequest' from JSON`,
  );
}

/** @internal */
export const MarkPaidInvoiceResponse$inboundSchema: z.ZodType<
  MarkPaidInvoiceResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: components.Invoice$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type MarkPaidInvoiceResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.Invoice$Outbound;
};

/** @internal */
export const MarkPaidInvoiceResponse$outboundSchema: z.ZodType<
  MarkPaidInvoiceResponse$Outbound,
  z.ZodTypeDef,
  MarkPaidInvoiceResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.Invoice$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function markPaidInvoiceResponseToJSON(
  markPaidInvoiceResponse: MarkPaidInvoiceResponse,
): string {
  return JSON.stringify(
    MarkPaidInvoiceResponse$outboundSchema.parse(markPaidInvoiceResponse),
  );
}
export function markPaidInvoiceResponseFromJSON(
  jsonString: string,
): SafeParseResult<MarkPaidInvoiceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MarkPaidInvoiceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MarkPaidInvoiceResponse' from JSON`,
  );
}
