/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateTicketRequest = {
  accountID: string;
  ticketID: string;
  updateTicket: components.UpdateTicket;
};

export type UpdateTicketResponse = {
  headers: { [k: string]: Array<string> };
  result: components.Ticket;
};

/** @internal */
export const UpdateTicketRequest$inboundSchema: z.ZodType<
  UpdateTicketRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  accountID: z.string(),
  ticketID: z.string(),
  UpdateTicket: components.UpdateTicket$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "UpdateTicket": "updateTicket",
  });
});
/** @internal */
export type UpdateTicketRequest$Outbound = {
  accountID: string;
  ticketID: string;
  UpdateTicket: components.UpdateTicket$Outbound;
};

/** @internal */
export const UpdateTicketRequest$outboundSchema: z.ZodType<
  UpdateTicketRequest$Outbound,
  z.ZodTypeDef,
  UpdateTicketRequest
> = z.object({
  accountID: z.string(),
  ticketID: z.string(),
  updateTicket: components.UpdateTicket$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    updateTicket: "UpdateTicket",
  });
});

export function updateTicketRequestToJSON(
  updateTicketRequest: UpdateTicketRequest,
): string {
  return JSON.stringify(
    UpdateTicketRequest$outboundSchema.parse(updateTicketRequest),
  );
}
export function updateTicketRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateTicketRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateTicketRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateTicketRequest' from JSON`,
  );
}

/** @internal */
export const UpdateTicketResponse$inboundSchema: z.ZodType<
  UpdateTicketResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: components.Ticket$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type UpdateTicketResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.Ticket$Outbound;
};

/** @internal */
export const UpdateTicketResponse$outboundSchema: z.ZodType<
  UpdateTicketResponse$Outbound,
  z.ZodTypeDef,
  UpdateTicketResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.Ticket$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function updateTicketResponseToJSON(
  updateTicketResponse: UpdateTicketResponse,
): string {
  return JSON.stringify(
    UpdateTicketResponse$outboundSchema.parse(updateTicketResponse),
  );
}
export function updateTicketResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateTicketResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateTicketResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateTicketResponse' from JSON`,
  );
}
