// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ACHPaymentSettings struct {
	// The description that shows up on ACH transactions. This will default to the account's display name on account creation.
	CompanyName string `json:"companyName"`
}

func (o *ACHPaymentSettings) GetCompanyName() string {
	if o == nil {
		return ""
	}
	return o.CompanyName
}
