// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AmountValidationError struct {
	Currency *string `json:"currency,omitempty"`
	Value    *string `json:"value,omitempty"`
}

func (o *AmountValidationError) GetCurrency() *string {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *AmountValidationError) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}
