// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BankAccountVerificationCreated struct {
	VerificationMethod BankAccountVerificationMethod `json:"verificationMethod"`
	Status             BankAccountVerificationStatus `json:"status"`
}

func (o *BankAccountVerificationCreated) GetVerificationMethod() BankAccountVerificationMethod {
	if o == nil {
		return BankAccountVerificationMethod("")
	}
	return o.VerificationMethod
}

func (o *BankAccountVerificationCreated) GetStatus() BankAccountVerificationStatus {
	if o == nil {
		return BankAccountVerificationStatus("")
	}
	return o.Status
}
