// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// CardBrand - The card brand.
type CardBrand string

const (
	CardBrandAmericanExpress CardBrand = "American Express"
	CardBrandDiscover        CardBrand = "Discover"
	CardBrandMastercard      CardBrand = "Mastercard"
	CardBrandVisa            CardBrand = "Visa"
	CardBrandUnknown         CardBrand = "Unknown"
)

func (e CardBrand) ToPointer() *CardBrand {
	return &e
}
func (e *CardBrand) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "American Express":
		fallthrough
	case "Discover":
		fallthrough
	case "Mastercard":
		fallthrough
	case "Visa":
		fallthrough
	case "Unknown":
		*e = CardBrand(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CardBrand: %v", v)
	}
}
