// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateEvidenceText struct {
	// The text to associate with the dispute as evidence.
	Text         string       `json:"text"`
	EvidenceType EvidenceType `json:"evidenceType"`
}

func (o *CreateEvidenceText) GetText() string {
	if o == nil {
		return ""
	}
	return o.Text
}

func (o *CreateEvidenceText) GetEvidenceType() EvidenceType {
	if o == nil {
		return EvidenceType("")
	}
	return o.EvidenceType
}
