// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateSweepConfig struct {
	WalletID string            `json:"walletID"`
	Status   SweepConfigStatus `json:"status"`
	// ID of the payment method.
	PushPaymentMethodID string `json:"pushPaymentMethodID"`
	// ID of the payment method.
	PullPaymentMethodID string `json:"pullPaymentMethodID"`
	// The text that appears on the banking statement. The default descriptor is a 10 character ID if an override is not set in the sweep configs statementDescriptor.
	StatementDescriptor *string `json:"statementDescriptor,omitempty"`
	MinimumBalance      *string `json:"minimumBalance,omitempty"`
}

func (o *CreateSweepConfig) GetWalletID() string {
	if o == nil {
		return ""
	}
	return o.WalletID
}

func (o *CreateSweepConfig) GetStatus() SweepConfigStatus {
	if o == nil {
		return SweepConfigStatus("")
	}
	return o.Status
}

func (o *CreateSweepConfig) GetPushPaymentMethodID() string {
	if o == nil {
		return ""
	}
	return o.PushPaymentMethodID
}

func (o *CreateSweepConfig) GetPullPaymentMethodID() string {
	if o == nil {
		return ""
	}
	return o.PullPaymentMethodID
}

func (o *CreateSweepConfig) GetStatementDescriptor() *string {
	if o == nil {
		return nil
	}
	return o.StatementDescriptor
}

func (o *CreateSweepConfig) GetMinimumBalance() *string {
	if o == nil {
		return nil
	}
	return o.MinimumBalance
}
