// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// FilePurpose - The file's purpose.
type FilePurpose string

const (
	FilePurposeBusinessVerification       FilePurpose = "business_verification"
	FilePurposeRepresentativeVerification FilePurpose = "representative_verification"
	FilePurposeIndividualVerification     FilePurpose = "individual_verification"
	FilePurposeMerchantUnderwriting       FilePurpose = "merchant_underwriting"
	FilePurposeAccountRequirement         FilePurpose = "account_requirement"
	FilePurposeIdentityVerification       FilePurpose = "identity_verification"
)

func (e FilePurpose) ToPointer() *FilePurpose {
	return &e
}
func (e *FilePurpose) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "business_verification":
		fallthrough
	case "representative_verification":
		fallthrough
	case "individual_verification":
		fallthrough
	case "merchant_underwriting":
		fallthrough
	case "account_requirement":
		fallthrough
	case "identity_verification":
		*e = FilePurpose(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FilePurpose: %v", v)
	}
}
