// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FulfillmentDetails struct {
	HasPhysicalGoods     bool             `json:"hasPhysicalGoods"`
	IsShippingProduct    bool             `json:"isShippingProduct"`
	ShipmentDurationDays int64            `json:"shipmentDurationDays"`
	ReturnPolicy         ReturnPolicyType `json:"returnPolicy"`
}

func (o *FulfillmentDetails) GetHasPhysicalGoods() bool {
	if o == nil {
		return false
	}
	return o.HasPhysicalGoods
}

func (o *FulfillmentDetails) GetIsShippingProduct() bool {
	if o == nil {
		return false
	}
	return o.IsShippingProduct
}

func (o *FulfillmentDetails) GetShipmentDurationDays() int64 {
	if o == nil {
		return 0
	}
	return o.ShipmentDurationDays
}

func (o *FulfillmentDetails) GetReturnPolicy() ReturnPolicyType {
	if o == nil {
		return ReturnPolicyType("")
	}
	return o.ReturnPolicy
}
