// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GeneratedByAccountID struct {
	AccountID *string `json:"AccountID,omitempty"`
}

func (o *GeneratedByAccountID) GetAccountID() *string {
	if o == nil {
		return nil
	}
	return o.AccountID
}
