// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GeneratedByDisputeID struct {
	DisputeID *string `json:"DisputeID,omitempty"`
}

func (o *GeneratedByDisputeID) GetDisputeID() *string {
	if o == nil {
		return nil
	}
	return o.DisputeID
}
