// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type InstitutionsSearchResponse struct {
	Ach  []ACHInstitution  `json:"ach"`
	Rtp  []RTPInstitution  `json:"rtp"`
	Wire []WireInstitution `json:"wire"`
}

func (o *InstitutionsSearchResponse) GetAch() []ACHInstitution {
	if o == nil {
		return []ACHInstitution{}
	}
	return o.Ach
}

func (o *InstitutionsSearchResponse) GetRtp() []RTPInstitution {
	if o == nil {
		return []RTPInstitution{}
	}
	return o.Rtp
}

func (o *InstitutionsSearchResponse) GetWire() []WireInstitution {
	if o == nil {
		return []WireInstitution{}
	}
	return o.Wire
}
