// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// MoovFeeDetails - Processing and pass-through costs that add up to the moovFee.
type MoovFeeDetails struct {
	// Card scheme fees accrued during authorization and settlement. String type represents dollars with up to 9 decimal place precision.
	CardScheme *string `json:"cardScheme,omitempty"`
	// Network interchange fee for Visa, Mastercard, or Discover. String type represents dollars with up to 9 decimal place precision.
	Interchange *string `json:"interchange,omitempty"`
	// Network discount fee for American Express. String type represents dollars with up to 9 decimal place precision.
	Discount *string `json:"discount,omitempty"`
	// Moov processing fee. String type represents dollars with up to 9 decimal place precision.
	MoovProcessing string `json:"moovProcessing"`
}

func (o *MoovFeeDetails) GetCardScheme() *string {
	if o == nil {
		return nil
	}
	return o.CardScheme
}

func (o *MoovFeeDetails) GetInterchange() *string {
	if o == nil {
		return nil
	}
	return o.Interchange
}

func (o *MoovFeeDetails) GetDiscount() *string {
	if o == nil {
		return nil
	}
	return o.Discount
}

func (o *MoovFeeDetails) GetMoovProcessing() string {
	if o == nil {
		return ""
	}
	return o.MoovProcessing
}
