// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
	"time"
)

type SweepConfig struct {
	SweepConfigID string            `json:"sweepConfigID"`
	WalletID      string            `json:"walletID"`
	Status        SweepConfigStatus `json:"status"`
	// The payment method used to push or pull funds to a bank account.
	// The push payment method can only be ach-credit-standard or ach-credit-same-day. The pull payment method can only be ach-debit-fund.
	PushPaymentMethod SweepConfigPaymentMethod `json:"pushPaymentMethod"`
	// The payment method used to push or pull funds to a bank account.
	// The push payment method can only be ach-credit-standard or ach-credit-same-day. The pull payment method can only be ach-debit-fund.
	PullPaymentMethod SweepConfigPaymentMethod `json:"pullPaymentMethod"`
	// An optional field to specify an amount to maintain in the wallet. This is a decimal-formatted numerical string that represents up to 2 decimal place precision. In USD for example, 12.34 is $12.34 and 0.99 is $0.99. If not supplied, the default is 0.00.
	MinimumBalance *string `json:"minimumBalance,omitempty"`
	// The text that appears on the banking statement. The default descriptor is a 10 character ID if an override is not set in the sweep configs statementDescriptor.
	StatementDescriptor *string `json:"statementDescriptor,omitempty"`
	// An array of fields that are locked. To request updates, please contact Moov support.
	LockedFields []string  `json:"lockedFields,omitempty"`
	CreatedOn    time.Time `json:"createdOn"`
	UpdatedOn    time.Time `json:"updatedOn"`
}

func (s SweepConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SweepConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SweepConfig) GetSweepConfigID() string {
	if o == nil {
		return ""
	}
	return o.SweepConfigID
}

func (o *SweepConfig) GetWalletID() string {
	if o == nil {
		return ""
	}
	return o.WalletID
}

func (o *SweepConfig) GetStatus() SweepConfigStatus {
	if o == nil {
		return SweepConfigStatus("")
	}
	return o.Status
}

func (o *SweepConfig) GetPushPaymentMethod() SweepConfigPaymentMethod {
	if o == nil {
		return SweepConfigPaymentMethod{}
	}
	return o.PushPaymentMethod
}

func (o *SweepConfig) GetPullPaymentMethod() SweepConfigPaymentMethod {
	if o == nil {
		return SweepConfigPaymentMethod{}
	}
	return o.PullPaymentMethod
}

func (o *SweepConfig) GetMinimumBalance() *string {
	if o == nil {
		return nil
	}
	return o.MinimumBalance
}

func (o *SweepConfig) GetStatementDescriptor() *string {
	if o == nil {
		return nil
	}
	return o.StatementDescriptor
}

func (o *SweepConfig) GetLockedFields() []string {
	if o == nil {
		return nil
	}
	return o.LockedFields
}

func (o *SweepConfig) GetCreatedOn() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedOn
}

func (o *SweepConfig) GetUpdatedOn() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedOn
}
