// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type SweepConfigStatus string

const (
	SweepConfigStatusEnabled  SweepConfigStatus = "enabled"
	SweepConfigStatusDisabled SweepConfigStatus = "disabled"
)

func (e SweepConfigStatus) ToPointer() *SweepConfigStatus {
	return &e
}
func (e *SweepConfigStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "enabled":
		fallthrough
	case "disabled":
		*e = SweepConfigStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SweepConfigStatus: %v", v)
	}
}
