// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// TokenType - An [RFC 6750](https://www.rfc-editor.org/rfc/rfc6750#section-6.1) token type.
type TokenType string

const (
	TokenTypeBearer TokenType = "Bearer"
)

func (e TokenType) ToPointer() *TokenType {
	return &e
}
func (e *TokenType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Bearer":
		*e = TokenType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TokenType: %v", v)
	}
}
