// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type TransferWaitFor string

const (
	TransferWaitForRailResponse TransferWaitFor = "rail-response"
)

func (e TransferWaitFor) ToPointer() *TransferWaitFor {
	return &e
}
func (e *TransferWaitFor) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "rail-response":
		*e = TransferWaitFor(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TransferWaitFor: %v", v)
	}
}
