// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type VolumeShareByCustomerType struct {
	Business *int `json:"business,omitempty"`
	Consumer *int `json:"consumer,omitempty"`
	P2p      *int `json:"p2p,omitempty"`
}

func (o *VolumeShareByCustomerType) GetBusiness() *int {
	if o == nil {
		return nil
	}
	return o.Business
}

func (o *VolumeShareByCustomerType) GetConsumer() *int {
	if o == nil {
		return nil
	}
	return o.Consumer
}

func (o *VolumeShareByCustomerType) GetP2p() *int {
	if o == nil {
		return nil
	}
	return o.P2p
}
