/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AmountDecimalUpdate,
  AmountDecimalUpdate$inboundSchema,
  AmountDecimalUpdate$Outbound,
  AmountDecimalUpdate$outboundSchema,
} from "./amountdecimalupdate.js";

export type AmountDetailsUpdate = {
  /**
   * The amount of tax applied to the invoice.
   */
  tax?: AmountDecimalUpdate | undefined;
  /**
   * The amount of surcharge applied to the invoice.
   */
  surcharge?: AmountDecimalUpdate | undefined;
};

/** @internal */
export const AmountDetailsUpdate$inboundSchema: z.ZodType<
  AmountDetailsUpdate,
  z.ZodTypeDef,
  unknown
> = z.object({
  tax: types.optional(AmountDecimalUpdate$inboundSchema),
  surcharge: types.optional(AmountDecimalUpdate$inboundSchema),
});
/** @internal */
export type AmountDetailsUpdate$Outbound = {
  tax?: AmountDecimalUpdate$Outbound | undefined;
  surcharge?: AmountDecimalUpdate$Outbound | undefined;
};

/** @internal */
export const AmountDetailsUpdate$outboundSchema: z.ZodType<
  AmountDetailsUpdate$Outbound,
  z.ZodTypeDef,
  AmountDetailsUpdate
> = z.object({
  tax: AmountDecimalUpdate$outboundSchema.optional(),
  surcharge: AmountDecimalUpdate$outboundSchema.optional(),
});

export function amountDetailsUpdateToJSON(
  amountDetailsUpdate: AmountDetailsUpdate,
): string {
  return JSON.stringify(
    AmountDetailsUpdate$outboundSchema.parse(amountDetailsUpdate),
  );
}
export function amountDetailsUpdateFromJSON(
  jsonString: string,
): SafeParseResult<AmountDetailsUpdate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AmountDetailsUpdate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AmountDetailsUpdate' from JSON`,
  );
}
