/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d490bd0a1e16
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AmountDecimalUpdate,
  AmountDecimalUpdate$inboundSchema,
  AmountDecimalUpdate$Outbound,
  AmountDecimalUpdate$outboundSchema,
} from "./amountdecimalupdate.js";

export type AmountDecimalRangeUpdate = {
  /**
   * Minimum amount allowed in the range
   */
  minimum?: AmountDecimalUpdate | undefined;
  /**
   * Maximum amount allowed in the range
   */
  maximum?: AmountDecimalUpdate | undefined;
};

/** @internal */
export const AmountDecimalRangeUpdate$inboundSchema: z.ZodType<
  AmountDecimalRangeUpdate,
  z.ZodTypeDef,
  unknown
> = z.object({
  minimum: types.optional(AmountDecimalUpdate$inboundSchema),
  maximum: types.optional(AmountDecimalUpdate$inboundSchema),
});
/** @internal */
export type AmountDecimalRangeUpdate$Outbound = {
  minimum?: AmountDecimalUpdate$Outbound | undefined;
  maximum?: AmountDecimalUpdate$Outbound | undefined;
};

/** @internal */
export const AmountDecimalRangeUpdate$outboundSchema: z.ZodType<
  AmountDecimalRangeUpdate$Outbound,
  z.ZodTypeDef,
  AmountDecimalRangeUpdate
> = z.object({
  minimum: AmountDecimalUpdate$outboundSchema.optional(),
  maximum: AmountDecimalUpdate$outboundSchema.optional(),
});

export function amountDecimalRangeUpdateToJSON(
  amountDecimalRangeUpdate: AmountDecimalRangeUpdate,
): string {
  return JSON.stringify(
    AmountDecimalRangeUpdate$outboundSchema.parse(amountDecimalRangeUpdate),
  );
}
export function amountDecimalRangeUpdateFromJSON(
  jsonString: string,
): SafeParseResult<AmountDecimalRangeUpdate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AmountDecimalRangeUpdate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AmountDecimalRangeUpdate' from JSON`,
  );
}
