/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * The reason the bank account status changed to the current value.
 */
export const BankAccountStatusReason = {
  BankAccountCreated: "bank-account-created",
  VerificationInitiated: "verification-initiated",
  MicroDepositAttemptsExceeded: "micro-deposit-attempts-exceeded",
  MicroDepositExpired: "micro-deposit-expired",
  MaxVerificationFailures: "max-verification-failures",
  VerificationAttemptsExceeded: "verification-attempts-exceeded",
  VerificationExpired: "verification-expired",
  VerificationSuccessful: "verification-successful",
  AchDebitReturn: "ach-debit-return",
  AchCreditReturn: "ach-credit-return",
  RtpCreditFailure: "rtp-credit-failure",
  FednowCreditFailure: "fednow-credit-failure",
  MicroDepositReturn: "micro-deposit-return",
  AdminAction: "admin-action",
  Other: "other",
} as const;
/**
 * The reason the bank account status changed to the current value.
 */
export type BankAccountStatusReason = OpenEnum<typeof BankAccountStatusReason>;

/** @internal */
export const BankAccountStatusReason$inboundSchema: z.ZodType<
  BankAccountStatusReason,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(BankAccountStatusReason);
/** @internal */
export const BankAccountStatusReason$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  BankAccountStatusReason
> = openEnums.outboundSchema(BankAccountStatusReason);
