/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8aeddd54df0a
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TransferTerminalCard,
  TransferTerminalCard$inboundSchema,
  TransferTerminalCard$Outbound,
  TransferTerminalCard$outboundSchema,
} from "./transferterminalcard.js";

/**
 * A card used at point of sale terminal for a card present transaction as contained within a payment method.
 */
export type CardPresentPaymentTransferPaymentMethod = {
  /**
   * ID of the payment method.
   */
  paymentMethodID: string;
  paymentMethodType: "card-present-payment";
  /**
   * Describes payment card details captured with tap or in-person payment.
   */
  terminalCard?: TransferTerminalCard | undefined;
};

/** @internal */
export const CardPresentPaymentTransferPaymentMethod$inboundSchema: z.ZodType<
  CardPresentPaymentTransferPaymentMethod,
  z.ZodTypeDef,
  unknown
> = z.object({
  paymentMethodID: types.string(),
  paymentMethodType: types.literal("card-present-payment"),
  terminalCard: types.optional(TransferTerminalCard$inboundSchema),
});
/** @internal */
export type CardPresentPaymentTransferPaymentMethod$Outbound = {
  paymentMethodID: string;
  paymentMethodType: "card-present-payment";
  terminalCard?: TransferTerminalCard$Outbound | undefined;
};

/** @internal */
export const CardPresentPaymentTransferPaymentMethod$outboundSchema: z.ZodType<
  CardPresentPaymentTransferPaymentMethod$Outbound,
  z.ZodTypeDef,
  CardPresentPaymentTransferPaymentMethod
> = z.object({
  paymentMethodID: z.string(),
  paymentMethodType: z.literal("card-present-payment"),
  terminalCard: TransferTerminalCard$outboundSchema.optional(),
});

export function cardPresentPaymentTransferPaymentMethodToJSON(
  cardPresentPaymentTransferPaymentMethod:
    CardPresentPaymentTransferPaymentMethod,
): string {
  return JSON.stringify(
    CardPresentPaymentTransferPaymentMethod$outboundSchema.parse(
      cardPresentPaymentTransferPaymentMethod,
    ),
  );
}
export function cardPresentPaymentTransferPaymentMethodFromJSON(
  jsonString: string,
): SafeParseResult<
  CardPresentPaymentTransferPaymentMethod,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CardPresentPaymentTransferPaymentMethod$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CardPresentPaymentTransferPaymentMethod' from JSON`,
  );
}
