/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 170d4b73a938
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * The card brand.
 */
export const CardBrand = {
  AmericanExpress: "American Express",
  Discover: "Discover",
  Mastercard: "Mastercard",
  Visa: "Visa",
  Unknown: "Unknown",
} as const;
/**
 * The card brand.
 */
export type CardBrand = OpenEnum<typeof CardBrand>;

/** @internal */
export const CardBrand$inboundSchema: z.ZodType<
  CardBrand,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(CardBrand);
/** @internal */
export const CardBrand$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  CardBrand
> = openEnums.outboundSchema(CardBrand);
