/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  E2EEToken,
  E2EEToken$inboundSchema,
  E2EEToken$Outbound,
  E2EEToken$outboundSchema,
} from "./e2eetoken.js";

export type CardMetadataRequest = {
  /**
   * Wraps a compact-serialized JSON Web Encryption (JWE) token used for secure transmission of sensitive data (e.g., PCI information) through intermediaries.
   *
   * @remarks
   * This token is encrypted using the public key from /end-to-end-keys and wraps an AES key. For details and examples, refer to our
   * [GitHub repository](https://github.com/moovfinancial/moov-go/blob/main/examples/e2ee/e2ee_test.go).
   */
  e2ee?: E2EEToken | undefined;
  /**
   * The full card number (PAN).
   */
  cardNumber?: string | undefined;
};

/** @internal */
export const CardMetadataRequest$inboundSchema: z.ZodType<
  CardMetadataRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  e2ee: types.optional(E2EEToken$inboundSchema),
  cardNumber: types.optional(types.string()),
});
/** @internal */
export type CardMetadataRequest$Outbound = {
  e2ee?: E2EEToken$Outbound | undefined;
  cardNumber?: string | undefined;
};

/** @internal */
export const CardMetadataRequest$outboundSchema: z.ZodType<
  CardMetadataRequest$Outbound,
  z.ZodTypeDef,
  CardMetadataRequest
> = z.object({
  e2ee: E2EEToken$outboundSchema.optional(),
  cardNumber: z.string().optional(),
});

export function cardMetadataRequestToJSON(
  cardMetadataRequest: CardMetadataRequest,
): string {
  return JSON.stringify(
    CardMetadataRequest$outboundSchema.parse(cardMetadataRequest),
  );
}
export function cardMetadataRequestFromJSON(
  jsonString: string,
): SafeParseResult<CardMetadataRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CardMetadataRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CardMetadataRequest' from JSON`,
  );
}
