/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  EnrichedIndustry,
  EnrichedIndustry$inboundSchema,
  EnrichedIndustry$Outbound,
  EnrichedIndustry$outboundSchema,
} from "./enrichedindustry.js";

export type EnrichedIndustries = {
  industries: Array<EnrichedIndustry>;
};

/** @internal */
export const EnrichedIndustries$inboundSchema: z.ZodType<
  EnrichedIndustries,
  z.ZodTypeDef,
  unknown
> = z.object({
  industries: z.array(EnrichedIndustry$inboundSchema),
});

/** @internal */
export type EnrichedIndustries$Outbound = {
  industries: Array<EnrichedIndustry$Outbound>;
};

/** @internal */
export const EnrichedIndustries$outboundSchema: z.ZodType<
  EnrichedIndustries$Outbound,
  z.ZodTypeDef,
  EnrichedIndustries
> = z.object({
  industries: z.array(EnrichedIndustry$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EnrichedIndustries$ {
  /** @deprecated use `EnrichedIndustries$inboundSchema` instead. */
  export const inboundSchema = EnrichedIndustries$inboundSchema;
  /** @deprecated use `EnrichedIndustries$outboundSchema` instead. */
  export const outboundSchema = EnrichedIndustries$outboundSchema;
  /** @deprecated use `EnrichedIndustries$Outbound` instead. */
  export type Outbound = EnrichedIndustries$Outbound;
}

export function enrichedIndustriesToJSON(
  enrichedIndustries: EnrichedIndustries,
): string {
  return JSON.stringify(
    EnrichedIndustries$outboundSchema.parse(enrichedIndustries),
  );
}

export function enrichedIndustriesFromJSON(
  jsonString: string,
): SafeParseResult<EnrichedIndustries, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EnrichedIndustries$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnrichedIndustries' from JSON`,
  );
}
