/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const FeePaidBy = {
  Source: "source",
  Destination: "destination",
} as const;
export type FeePaidBy = OpenEnum<typeof FeePaidBy>;

/** @internal */
export const FeePaidBy$inboundSchema: z.ZodType<
  FeePaidBy,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(FeePaidBy);
/** @internal */
export const FeePaidBy$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  FeePaidBy
> = openEnums.outboundSchema(FeePaidBy);
