/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type IndustryCodesUpdate = {
  naics?: string | undefined;
  sic?: string | undefined;
  mcc?: string | undefined;
};

/** @internal */
export const IndustryCodesUpdate$inboundSchema: z.ZodType<
  IndustryCodesUpdate,
  z.ZodTypeDef,
  unknown
> = z.object({
  naics: z.string().optional(),
  sic: z.string().optional(),
  mcc: z.string().optional(),
});

/** @internal */
export type IndustryCodesUpdate$Outbound = {
  naics?: string | undefined;
  sic?: string | undefined;
  mcc?: string | undefined;
};

/** @internal */
export const IndustryCodesUpdate$outboundSchema: z.ZodType<
  IndustryCodesUpdate$Outbound,
  z.ZodTypeDef,
  IndustryCodesUpdate
> = z.object({
  naics: z.string().optional(),
  sic: z.string().optional(),
  mcc: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IndustryCodesUpdate$ {
  /** @deprecated use `IndustryCodesUpdate$inboundSchema` instead. */
  export const inboundSchema = IndustryCodesUpdate$inboundSchema;
  /** @deprecated use `IndustryCodesUpdate$outboundSchema` instead. */
  export const outboundSchema = IndustryCodesUpdate$outboundSchema;
  /** @deprecated use `IndustryCodesUpdate$Outbound` instead. */
  export type Outbound = IndustryCodesUpdate$Outbound;
}

export function industryCodesUpdateToJSON(
  industryCodesUpdate: IndustryCodesUpdate,
): string {
  return JSON.stringify(
    IndustryCodesUpdate$outboundSchema.parse(industryCodesUpdate),
  );
}

export function industryCodesUpdateFromJSON(
  jsonString: string,
): SafeParseResult<IndustryCodesUpdate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IndustryCodesUpdate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IndustryCodesUpdate' from JSON`,
  );
}
