/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 61b655e8783d
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Status codes for instant-bank failures.
 */
export const InstantBankFailureCode = {
  ProcessingError: "processing-error",
  InvalidAccount: "invalid-account",
  AccountClosed: "account-closed",
  AccountBlocked: "account-blocked",
  InvalidField: "invalid-field",
  TransactionNotSupported: "transaction-not-supported",
  LimitExceeded: "limit-exceeded",
  InvalidAmount: "invalid-amount",
  CustomerDeceased: "customer-deceased",
  ParticipantNotAvailable: "participant-not-available",
  Other: "other",
} as const;
/**
 * Status codes for instant-bank failures.
 */
export type InstantBankFailureCode = OpenEnum<typeof InstantBankFailureCode>;

/** @internal */
export const InstantBankFailureCode$inboundSchema: z.ZodType<
  InstantBankFailureCode,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(InstantBankFailureCode);
/** @internal */
export const InstantBankFailureCode$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  InstantBankFailureCode
> = openEnums.outboundSchema(InstantBankFailureCode);
