/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Status codes for instant-bank failures.
 */
export const InstantBankFailureCode = {
  ProcessingError: "processing-error",
  InvalidAccount: "invalid-account",
  AccountClosed: "account-closed",
  AccountBlocked: "account-blocked",
  InvalidField: "invalid-field",
  TransactionNotSupported: "transaction-not-supported",
  LimitExceeded: "limit-exceeded",
  InvalidAmount: "invalid-amount",
  CustomerDeceased: "customer-deceased",
  ParticipantNotAvailable: "participant-not-available",
  Other: "other",
} as const;
/**
 * Status codes for instant-bank failures.
 */
export type InstantBankFailureCode = ClosedEnum<typeof InstantBankFailureCode>;

/** @internal */
export const InstantBankFailureCode$inboundSchema: z.ZodNativeEnum<
  typeof InstantBankFailureCode
> = z.nativeEnum(InstantBankFailureCode);
/** @internal */
export const InstantBankFailureCode$outboundSchema: z.ZodNativeEnum<
  typeof InstantBankFailureCode
> = InstantBankFailureCode$inboundSchema;
