/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type InvoiceLineItemImageMetadata = {
  /**
   * A unique identifier for a Moov resource. Supports UUID format (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx) or typed format with base32-encoded UUID and type suffix (e.g., kuoaydiojf7uszaokc2ggnaaaa_xfer).
   */
  imageID: string;
  /**
   * Alternative text for the image.
   */
  altText?: string | undefined;
  /**
   * The image's public URL.
   */
  link: string;
  /**
   * A unique identifier for an image, used in public image links.
   */
  publicID: string;
};

/** @internal */
export const InvoiceLineItemImageMetadata$inboundSchema: z.ZodType<
  InvoiceLineItemImageMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  imageID: types.string(),
  altText: types.optional(types.string()),
  link: types.string(),
  publicID: types.string(),
});
/** @internal */
export type InvoiceLineItemImageMetadata$Outbound = {
  imageID: string;
  altText?: string | undefined;
  link: string;
  publicID: string;
};

/** @internal */
export const InvoiceLineItemImageMetadata$outboundSchema: z.ZodType<
  InvoiceLineItemImageMetadata$Outbound,
  z.ZodTypeDef,
  InvoiceLineItemImageMetadata
> = z.object({
  imageID: z.string(),
  altText: z.string().optional(),
  link: z.string(),
  publicID: z.string(),
});

export function invoiceLineItemImageMetadataToJSON(
  invoiceLineItemImageMetadata: InvoiceLineItemImageMetadata,
): string {
  return JSON.stringify(
    InvoiceLineItemImageMetadata$outboundSchema.parse(
      invoiceLineItemImageMetadata,
    ),
  );
}
export function invoiceLineItemImageMetadataFromJSON(
  jsonString: string,
): SafeParseResult<InvoiceLineItemImageMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvoiceLineItemImageMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvoiceLineItemImageMetadata' from JSON`,
  );
}
