/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  GooglePayResponse,
  GooglePayResponse$inboundSchema,
  GooglePayResponse$Outbound,
  GooglePayResponse$outboundSchema,
} from "./googlepayresponse.js";
import {
  PaymentMethodType,
  PaymentMethodType$inboundSchema,
  PaymentMethodType$outboundSchema,
} from "./paymentmethodtype.js";

export type LinkedGooglePayPaymentMethod = {
  /**
   * The new payment method's ID.
   */
  paymentMethodID: string;
  /**
   * The payment method type that represents a payment rail and directionality
   */
  paymentMethodType: PaymentMethodType;
  /**
   * Describes a Google Pay token on a Moov account.
   */
  googlePay: GooglePayResponse;
};

/** @internal */
export const LinkedGooglePayPaymentMethod$inboundSchema: z.ZodType<
  LinkedGooglePayPaymentMethod,
  z.ZodTypeDef,
  unknown
> = z.object({
  paymentMethodID: z.string(),
  paymentMethodType: PaymentMethodType$inboundSchema,
  googlePay: GooglePayResponse$inboundSchema,
});
/** @internal */
export type LinkedGooglePayPaymentMethod$Outbound = {
  paymentMethodID: string;
  paymentMethodType: string;
  googlePay: GooglePayResponse$Outbound;
};

/** @internal */
export const LinkedGooglePayPaymentMethod$outboundSchema: z.ZodType<
  LinkedGooglePayPaymentMethod$Outbound,
  z.ZodTypeDef,
  LinkedGooglePayPaymentMethod
> = z.object({
  paymentMethodID: z.string(),
  paymentMethodType: PaymentMethodType$outboundSchema,
  googlePay: GooglePayResponse$outboundSchema,
});

export function linkedGooglePayPaymentMethodToJSON(
  linkedGooglePayPaymentMethod: LinkedGooglePayPaymentMethod,
): string {
  return JSON.stringify(
    LinkedGooglePayPaymentMethod$outboundSchema.parse(
      linkedGooglePayPaymentMethod,
    ),
  );
}
export function linkedGooglePayPaymentMethodFromJSON(
  jsonString: string,
): SafeParseResult<LinkedGooglePayPaymentMethod, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LinkedGooglePayPaymentMethod$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LinkedGooglePayPaymentMethod' from JSON`,
  );
}
