/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  WalletStatus,
  WalletStatus$inboundSchema,
  WalletStatus$outboundSchema,
} from "./walletstatus.js";

export type PatchWallet = {
  name?: string | undefined;
  /**
   * Status of a wallet.
   *
   * @remarks
   *   - `active`: The wallet is available for use and has an enabled payment method.
   *   - `closed`: The wallet is no longer active and the corresponding payment method has been disabled.
   */
  status?: WalletStatus | undefined;
  description?: string | null | undefined;
  metadata?: { [k: string]: string } | null | undefined;
};

/** @internal */
export const PatchWallet$inboundSchema: z.ZodType<
  PatchWallet,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: types.optional(types.string()),
  status: types.optional(WalletStatus$inboundSchema),
  description: z.nullable(types.string()).optional(),
  metadata: z.nullable(z.record(types.string())).optional(),
});
/** @internal */
export type PatchWallet$Outbound = {
  name?: string | undefined;
  status?: string | undefined;
  description?: string | null | undefined;
  metadata?: { [k: string]: string } | null | undefined;
};

/** @internal */
export const PatchWallet$outboundSchema: z.ZodType<
  PatchWallet$Outbound,
  z.ZodTypeDef,
  PatchWallet
> = z.object({
  name: z.string().optional(),
  status: WalletStatus$outboundSchema.optional(),
  description: z.nullable(z.string()).optional(),
  metadata: z.nullable(z.record(z.string())).optional(),
});

export function patchWalletToJSON(patchWallet: PatchWallet): string {
  return JSON.stringify(PatchWallet$outboundSchema.parse(patchWallet));
}
export function patchWalletFromJSON(
  jsonString: string,
): SafeParseResult<PatchWallet, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchWallet$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchWallet' from JSON`,
  );
}
