/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AmountDecimal,
  AmountDecimal$inboundSchema,
  AmountDecimal$Outbound,
  AmountDecimal$outboundSchema,
} from "./amountdecimal.js";

export type PaymentLinkAmountDetails = {
  /**
   * The amount of tax applied to the payment link.
   */
  tax?: AmountDecimal | undefined;
};

/** @internal */
export const PaymentLinkAmountDetails$inboundSchema: z.ZodType<
  PaymentLinkAmountDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  tax: types.optional(AmountDecimal$inboundSchema),
});
/** @internal */
export type PaymentLinkAmountDetails$Outbound = {
  tax?: AmountDecimal$Outbound | undefined;
};

/** @internal */
export const PaymentLinkAmountDetails$outboundSchema: z.ZodType<
  PaymentLinkAmountDetails$Outbound,
  z.ZodTypeDef,
  PaymentLinkAmountDetails
> = z.object({
  tax: AmountDecimal$outboundSchema.optional(),
});

export function paymentLinkAmountDetailsToJSON(
  paymentLinkAmountDetails: PaymentLinkAmountDetails,
): string {
  return JSON.stringify(
    PaymentLinkAmountDetails$outboundSchema.parse(paymentLinkAmountDetails),
  );
}
export function paymentLinkAmountDetailsFromJSON(
  jsonString: string,
): SafeParseResult<PaymentLinkAmountDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentLinkAmountDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentLinkAmountDetails' from JSON`,
  );
}
