/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PaymentLinkLineItem,
  PaymentLinkLineItem$inboundSchema,
  PaymentLinkLineItem$Outbound,
  PaymentLinkLineItem$outboundSchema,
} from "./paymentlinklineitem.js";

/**
 * An optional collection of line items for a payment link.
 *
 * @remarks
 * When line items are provided, their total plus sales tax must equal the payment link amount.
 */
export type PaymentLinkLineItemsUpdate = {
  /**
   * The list of line items.
   */
  items?: Array<PaymentLinkLineItem> | undefined;
};

/** @internal */
export const PaymentLinkLineItemsUpdate$inboundSchema: z.ZodType<
  PaymentLinkLineItemsUpdate,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(PaymentLinkLineItem$inboundSchema).optional(),
});
/** @internal */
export type PaymentLinkLineItemsUpdate$Outbound = {
  items?: Array<PaymentLinkLineItem$Outbound> | undefined;
};

/** @internal */
export const PaymentLinkLineItemsUpdate$outboundSchema: z.ZodType<
  PaymentLinkLineItemsUpdate$Outbound,
  z.ZodTypeDef,
  PaymentLinkLineItemsUpdate
> = z.object({
  items: z.array(PaymentLinkLineItem$outboundSchema).optional(),
});

export function paymentLinkLineItemsUpdateToJSON(
  paymentLinkLineItemsUpdate: PaymentLinkLineItemsUpdate,
): string {
  return JSON.stringify(
    PaymentLinkLineItemsUpdate$outboundSchema.parse(paymentLinkLineItemsUpdate),
  );
}
export function paymentLinkLineItemsUpdateFromJSON(
  jsonString: string,
): SafeParseResult<PaymentLinkLineItemsUpdate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentLinkLineItemsUpdate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentLinkLineItemsUpdate' from JSON`,
  );
}
