/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CardTransactionFailureCode,
  CardTransactionFailureCode$inboundSchema,
  CardTransactionFailureCode$outboundSchema,
} from "./cardtransactionfailurecode.js";

export type PushToCardTransferProcessingDetails = {
  authorizationCode?: string | undefined;
  networkTransactionID?: string | undefined;
  networkResponseCode?: string | undefined;
  failureCode?: CardTransactionFailureCode | undefined;
};

/** @internal */
export const PushToCardTransferProcessingDetails$inboundSchema: z.ZodType<
  PushToCardTransferProcessingDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  authorizationCode: types.optional(types.string()),
  networkTransactionID: types.optional(types.string()),
  networkResponseCode: types.optional(types.string()),
  failureCode: types.optional(CardTransactionFailureCode$inboundSchema),
});
/** @internal */
export type PushToCardTransferProcessingDetails$Outbound = {
  authorizationCode?: string | undefined;
  networkTransactionID?: string | undefined;
  networkResponseCode?: string | undefined;
  failureCode?: string | undefined;
};

/** @internal */
export const PushToCardTransferProcessingDetails$outboundSchema: z.ZodType<
  PushToCardTransferProcessingDetails$Outbound,
  z.ZodTypeDef,
  PushToCardTransferProcessingDetails
> = z.object({
  authorizationCode: z.string().optional(),
  networkTransactionID: z.string().optional(),
  networkResponseCode: z.string().optional(),
  failureCode: CardTransactionFailureCode$outboundSchema.optional(),
});

export function pushToCardTransferProcessingDetailsToJSON(
  pushToCardTransferProcessingDetails: PushToCardTransferProcessingDetails,
): string {
  return JSON.stringify(
    PushToCardTransferProcessingDetails$outboundSchema.parse(
      pushToCardTransferProcessingDetails,
    ),
  );
}
export function pushToCardTransferProcessingDetailsFromJSON(
  jsonString: string,
): SafeParseResult<PushToCardTransferProcessingDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PushToCardTransferProcessingDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PushToCardTransferProcessingDetails' from JSON`,
  );
}
