/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AmountDecimal,
  AmountDecimal$inboundSchema,
  AmountDecimal$Outbound,
  AmountDecimal$outboundSchema,
} from "./amountdecimal.js";

export type RefundAmountDetails = {
  /**
   * The amount of surcharge to refund. Should be proportionate to the surcharge on the original transfer
   */
  surcharge?: AmountDecimal | undefined;
};

/** @internal */
export const RefundAmountDetails$inboundSchema: z.ZodType<
  RefundAmountDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  surcharge: types.optional(AmountDecimal$inboundSchema),
});
/** @internal */
export type RefundAmountDetails$Outbound = {
  surcharge?: AmountDecimal$Outbound | undefined;
};

/** @internal */
export const RefundAmountDetails$outboundSchema: z.ZodType<
  RefundAmountDetails$Outbound,
  z.ZodTypeDef,
  RefundAmountDetails
> = z.object({
  surcharge: AmountDecimal$outboundSchema.optional(),
});

export function refundAmountDetailsToJSON(
  refundAmountDetails: RefundAmountDetails,
): string {
  return JSON.stringify(
    RefundAmountDetails$outboundSchema.parse(refundAmountDetails),
  );
}
export function refundAmountDetailsFromJSON(
  jsonString: string,
): SafeParseResult<RefundAmountDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RefundAmountDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RefundAmountDetails' from JSON`,
  );
}
