/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AmountDecimal,
  AmountDecimal$inboundSchema,
  AmountDecimal$Outbound,
  AmountDecimal$outboundSchema,
} from "./amountdecimal.js";

export type ReversalAmountDetails = {
  /**
   * The amount of surcharge to refund. Should be proportionate to the surcharge on the original transfer. This does not reply if the reversal resulted in a cancellation instead of a refund
   */
  surcharge?: AmountDecimal | undefined;
};

/** @internal */
export const ReversalAmountDetails$inboundSchema: z.ZodType<
  ReversalAmountDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  surcharge: types.optional(AmountDecimal$inboundSchema),
});
/** @internal */
export type ReversalAmountDetails$Outbound = {
  surcharge?: AmountDecimal$Outbound | undefined;
};

/** @internal */
export const ReversalAmountDetails$outboundSchema: z.ZodType<
  ReversalAmountDetails$Outbound,
  z.ZodTypeDef,
  ReversalAmountDetails
> = z.object({
  surcharge: AmountDecimal$outboundSchema.optional(),
});

export function reversalAmountDetailsToJSON(
  reversalAmountDetails: ReversalAmountDetails,
): string {
  return JSON.stringify(
    ReversalAmountDetails$outboundSchema.parse(reversalAmountDetails),
  );
}
export function reversalAmountDetailsFromJSON(
  jsonString: string,
): SafeParseResult<ReversalAmountDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReversalAmountDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReversalAmountDetails' from JSON`,
  );
}
