/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TransferPaymentMethodsBankAccount,
  TransferPaymentMethodsBankAccount$inboundSchema,
  TransferPaymentMethodsBankAccount$Outbound,
  TransferPaymentMethodsBankAccount$outboundSchema,
} from "./transferpaymentmethodsbankaccount.js";

export type RtpCreditTransferPaymentMethod = {
  /**
   * ID of the payment method.
   */
  paymentMethodID: string;
  paymentMethodType: "rtp-credit";
  /**
   * A bank account as contained within a payment method.
   */
  bankAccount: TransferPaymentMethodsBankAccount;
};

/** @internal */
export const RtpCreditTransferPaymentMethod$inboundSchema: z.ZodType<
  RtpCreditTransferPaymentMethod,
  z.ZodTypeDef,
  unknown
> = z.object({
  paymentMethodID: z.string(),
  paymentMethodType: z.literal("rtp-credit"),
  bankAccount: TransferPaymentMethodsBankAccount$inboundSchema,
});
/** @internal */
export type RtpCreditTransferPaymentMethod$Outbound = {
  paymentMethodID: string;
  paymentMethodType: "rtp-credit";
  bankAccount: TransferPaymentMethodsBankAccount$Outbound;
};

/** @internal */
export const RtpCreditTransferPaymentMethod$outboundSchema: z.ZodType<
  RtpCreditTransferPaymentMethod$Outbound,
  z.ZodTypeDef,
  RtpCreditTransferPaymentMethod
> = z.object({
  paymentMethodID: z.string(),
  paymentMethodType: z.literal("rtp-credit"),
  bankAccount: TransferPaymentMethodsBankAccount$outboundSchema,
});

export function rtpCreditTransferPaymentMethodToJSON(
  rtpCreditTransferPaymentMethod: RtpCreditTransferPaymentMethod,
): string {
  return JSON.stringify(
    RtpCreditTransferPaymentMethod$outboundSchema.parse(
      rtpCreditTransferPaymentMethod,
    ),
  );
}
export function rtpCreditTransferPaymentMethodFromJSON(
  jsonString: string,
): SafeParseResult<RtpCreditTransferPaymentMethod, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RtpCreditTransferPaymentMethod$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RtpCreditTransferPaymentMethod' from JSON`,
  );
}
