/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const SweepStatus = {
  Accruing: "accruing",
  ActionRequired: "action-required",
  Canceled: "canceled",
  Closed: "closed",
  Failed: "failed",
  Paid: "paid",
} as const;
export type SweepStatus = OpenEnum<typeof SweepStatus>;

/** @internal */
export const SweepStatus$inboundSchema: z.ZodType<
  SweepStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(SweepStatus);
/** @internal */
export const SweepStatus$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  SweepStatus
> = openEnums.outboundSchema(SweepStatus);
