/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ACHTransactionDetails,
  ACHTransactionDetails$inboundSchema,
  ACHTransactionDetails$Outbound,
  ACHTransactionDetails$outboundSchema,
} from "./achtransactiondetails.js";
import {
  BankAccount,
  BankAccount$inboundSchema,
  BankAccount$Outbound,
  BankAccount$outboundSchema,
} from "./bankaccount.js";
import {
  CardTransactionDetails,
  CardTransactionDetails$inboundSchema,
  CardTransactionDetails$Outbound,
  CardTransactionDetails$outboundSchema,
} from "./cardtransactiondetails.js";
import {
  TransferAccount,
  TransferAccount$inboundSchema,
  TransferAccount$Outbound,
  TransferAccount$outboundSchema,
} from "./transferaccount.js";

export type TransferSource = {
  paymentMethodID: string;
  paymentMethodType: string;
  account: TransferAccount;
  /**
   * Describes a bank account linked to a Moov account.
   */
  bankAccount?: BankAccount | undefined;
  wallet?: any | undefined;
  card?: any | undefined;
  applePay?: any | undefined;
  /**
   * Card-specific details about the transaction.
   */
  cardDetails?: CardTransactionDetails | undefined;
  /**
   * ACH specific details about the transaction.
   */
  achDetails?: ACHTransactionDetails | undefined;
};

/** @internal */
export const TransferSource$inboundSchema: z.ZodType<
  TransferSource,
  z.ZodTypeDef,
  unknown
> = z.object({
  paymentMethodID: z.string(),
  paymentMethodType: z.string(),
  account: TransferAccount$inboundSchema,
  bankAccount: BankAccount$inboundSchema.optional(),
  wallet: z.any().optional(),
  card: z.any().optional(),
  applePay: z.any().optional(),
  cardDetails: CardTransactionDetails$inboundSchema.optional(),
  achDetails: ACHTransactionDetails$inboundSchema.optional(),
});

/** @internal */
export type TransferSource$Outbound = {
  paymentMethodID: string;
  paymentMethodType: string;
  account: TransferAccount$Outbound;
  bankAccount?: BankAccount$Outbound | undefined;
  wallet?: any | undefined;
  card?: any | undefined;
  applePay?: any | undefined;
  cardDetails?: CardTransactionDetails$Outbound | undefined;
  achDetails?: ACHTransactionDetails$Outbound | undefined;
};

/** @internal */
export const TransferSource$outboundSchema: z.ZodType<
  TransferSource$Outbound,
  z.ZodTypeDef,
  TransferSource
> = z.object({
  paymentMethodID: z.string(),
  paymentMethodType: z.string(),
  account: TransferAccount$outboundSchema,
  bankAccount: BankAccount$outboundSchema.optional(),
  wallet: z.any().optional(),
  card: z.any().optional(),
  applePay: z.any().optional(),
  cardDetails: CardTransactionDetails$outboundSchema.optional(),
  achDetails: ACHTransactionDetails$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TransferSource$ {
  /** @deprecated use `TransferSource$inboundSchema` instead. */
  export const inboundSchema = TransferSource$inboundSchema;
  /** @deprecated use `TransferSource$outboundSchema` instead. */
  export const outboundSchema = TransferSource$outboundSchema;
  /** @deprecated use `TransferSource$Outbound` instead. */
  export type Outbound = TransferSource$Outbound;
}

export function transferSourceToJSON(transferSource: TransferSource): string {
  return JSON.stringify(TransferSource$outboundSchema.parse(transferSource));
}

export function transferSourceFromJSON(
  jsonString: string,
): SafeParseResult<TransferSource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransferSource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransferSource' from JSON`,
  );
}
