/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AmountDetailsUpdate,
  AmountDetailsUpdate$inboundSchema,
  AmountDetailsUpdate$Outbound,
  AmountDetailsUpdate$outboundSchema,
} from "./amountdetailsupdate.js";
import {
  CreateInvoiceLineItemsUpdate,
  CreateInvoiceLineItemsUpdate$inboundSchema,
  CreateInvoiceLineItemsUpdate$Outbound,
  CreateInvoiceLineItemsUpdate$outboundSchema,
} from "./createinvoicelineitemsupdate.js";
import {
  InvoiceStatus,
  InvoiceStatus$inboundSchema,
  InvoiceStatus$outboundSchema,
} from "./invoicestatus.js";

export type UpdateInvoice = {
  description?: string | undefined;
  /**
   * A collection of line items for an invoice.
   */
  lineItems?: CreateInvoiceLineItemsUpdate | undefined;
  invoiceDate?: Date | null | undefined;
  dueDate?: Date | null | undefined;
  /**
   *   The status can be updated to one of the following values under specific conditions:
   *
   * @remarks
   *   - `canceled`: Can only be set if the current status is `draft`, `unpaid`, or `overdue`. Canceling an invoice
   *     indicates the invoice is no longer expected to be paid (e.g., the charge was waived or terms changed).
   *     Canceled invoices still appear in list results by default and remain part of the invoice history.
   *     To completely discard an invoice created by mistake, use the delete endpoint instead.
   *   - `unpaid`: Can only be set if the current status is `draft`. Setting the status to `unpaid` finalizes the invoice and sends an email with a payment link to the customer.
   */
  status?: InvoiceStatus | undefined;
  amountDetails?: AmountDetailsUpdate | undefined;
};

/** @internal */
export const UpdateInvoice$inboundSchema: z.ZodType<
  UpdateInvoice,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: types.optional(types.string()),
  lineItems: types.optional(CreateInvoiceLineItemsUpdate$inboundSchema),
  invoiceDate: z.nullable(types.date()).optional(),
  dueDate: z.nullable(types.date()).optional(),
  status: types.optional(InvoiceStatus$inboundSchema),
  amountDetails: types.optional(AmountDetailsUpdate$inboundSchema),
});
/** @internal */
export type UpdateInvoice$Outbound = {
  description?: string | undefined;
  lineItems?: CreateInvoiceLineItemsUpdate$Outbound | undefined;
  invoiceDate?: string | null | undefined;
  dueDate?: string | null | undefined;
  status?: string | undefined;
  amountDetails?: AmountDetailsUpdate$Outbound | undefined;
};

/** @internal */
export const UpdateInvoice$outboundSchema: z.ZodType<
  UpdateInvoice$Outbound,
  z.ZodTypeDef,
  UpdateInvoice
> = z.object({
  description: z.string().optional(),
  lineItems: CreateInvoiceLineItemsUpdate$outboundSchema.optional(),
  invoiceDate: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  dueDate: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  status: InvoiceStatus$outboundSchema.optional(),
  amountDetails: AmountDetailsUpdate$outboundSchema.optional(),
});

export function updateInvoiceToJSON(updateInvoice: UpdateInvoice): string {
  return JSON.stringify(UpdateInvoice$outboundSchema.parse(updateInvoice));
}
export function updateInvoiceFromJSON(
  jsonString: string,
): SafeParseResult<UpdateInvoice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateInvoice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateInvoice' from JSON`,
  );
}
