/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  IssuingControlsRestrictionMode,
  IssuingControlsRestrictionMode$inboundSchema,
  IssuingControlsRestrictionMode$outboundSchema,
} from "./issuingcontrolsrestrictionmode.js";
import {
  IssuingMerchantCategory,
  IssuingMerchantCategory$inboundSchema,
  IssuingMerchantCategory$outboundSchema,
} from "./issuingmerchantcategory.js";
import {
  IssuingVelocityLimit,
  IssuingVelocityLimit$inboundSchema,
  IssuingVelocityLimit$Outbound,
  IssuingVelocityLimit$outboundSchema,
} from "./issuingvelocitylimit.js";
import {
  MerchantEntry,
  MerchantEntry$inboundSchema,
  MerchantEntry$Outbound,
  MerchantEntry$outboundSchema,
} from "./merchantentry.js";
import {
  ScheduleWindow,
  ScheduleWindow$inboundSchema,
  ScheduleWindow$Outbound,
  ScheduleWindow$outboundSchema,
} from "./schedulewindow.js";

/**
 * Replaces the merchant category restrictions. Set to `null` to remove.
 */
export type UpdateIssuingControlsMerchantCategoryRestrictions = {
  /**
   * Whether the listed categories are the only ones allowed, or the ones to block.
   */
  mode?: IssuingControlsRestrictionMode | undefined;
  /**
   * Predefined category groups to allow or block.
   */
  categories?: Array<IssuingMerchantCategory> | undefined;
  /**
   * Individual merchant category codes (MCCs) to allow or block, for codes not covered by a predefined category.
   */
  customMCCs?: Array<string> | undefined;
  /**
   * Merchants that are exempt from category restrictions regardless of their category.
   */
  exemptMerchants?: Array<MerchantEntry> | undefined;
};

/**
 * Replaces the merchant restrictions. Set to `null` to remove.
 */
export type UpdateIssuingControlsMerchantRestrictions = {
  /**
   * Whether the listed merchants are the only ones allowed, or the ones to block.
   */
  mode?: IssuingControlsRestrictionMode | undefined;
  /**
   * The merchants to allow or block.
   */
  merchants?: Array<MerchantEntry> | undefined;
};

/**
 * Replaces the allowed schedule. Set to `null` to remove all schedule restrictions.
 */
export type UpdateIssuingControlsAllowedSchedule = {
  /**
   * IANA timezone string used to evaluate window boundaries against the authorization time.
   */
  timezone?: string | undefined;
  /**
   * Time windows during which the card may authorize. Any matching window allows the transaction.
   */
  windows?: Array<ScheduleWindow> | undefined;
};

/**
 * Mutable spend controls. Each field replaces the entire corresponding value.
 */
export type UpdateIssuingControls = {
  /**
   * Replaces the entire set of velocity limits. Send an empty array to clear all limits.
   */
  velocityLimits?: Array<IssuingVelocityLimit> | undefined;
  /**
   * Replaces the merchant category restrictions. Set to `null` to remove.
   */
  merchantCategoryRestrictions?:
    | UpdateIssuingControlsMerchantCategoryRestrictions
    | null
    | undefined;
  /**
   * Replaces the merchant restrictions. Set to `null` to remove.
   */
  merchantRestrictions?:
    | UpdateIssuingControlsMerchantRestrictions
    | null
    | undefined;
  /**
   * Replaces the allowed schedule. Set to `null` to remove all schedule restrictions.
   */
  allowedSchedule?: UpdateIssuingControlsAllowedSchedule | null | undefined;
  /**
   * A spend cutoff date and time. Set to `null` to remove the cutoff.
   */
  expiresOn?: Date | null | undefined;
};

/** @internal */
export const UpdateIssuingControlsMerchantCategoryRestrictions$inboundSchema:
  z.ZodType<
    UpdateIssuingControlsMerchantCategoryRestrictions,
    z.ZodTypeDef,
    unknown
  > = z.object({
    mode: types.optional(IssuingControlsRestrictionMode$inboundSchema),
    categories: types.optional(z.array(IssuingMerchantCategory$inboundSchema)),
    customMCCs: types.optional(z.array(types.string())),
    exemptMerchants: types.optional(z.array(MerchantEntry$inboundSchema)),
  });
/** @internal */
export type UpdateIssuingControlsMerchantCategoryRestrictions$Outbound = {
  mode?: string | undefined;
  categories?: Array<string> | undefined;
  customMCCs?: Array<string> | undefined;
  exemptMerchants?: Array<MerchantEntry$Outbound> | undefined;
};

/** @internal */
export const UpdateIssuingControlsMerchantCategoryRestrictions$outboundSchema:
  z.ZodType<
    UpdateIssuingControlsMerchantCategoryRestrictions$Outbound,
    z.ZodTypeDef,
    UpdateIssuingControlsMerchantCategoryRestrictions
  > = z.object({
    mode: IssuingControlsRestrictionMode$outboundSchema.optional(),
    categories: z.array(IssuingMerchantCategory$outboundSchema).optional(),
    customMCCs: z.array(z.string()).optional(),
    exemptMerchants: z.array(MerchantEntry$outboundSchema).optional(),
  });

export function updateIssuingControlsMerchantCategoryRestrictionsToJSON(
  updateIssuingControlsMerchantCategoryRestrictions:
    UpdateIssuingControlsMerchantCategoryRestrictions,
): string {
  return JSON.stringify(
    UpdateIssuingControlsMerchantCategoryRestrictions$outboundSchema.parse(
      updateIssuingControlsMerchantCategoryRestrictions,
    ),
  );
}
export function updateIssuingControlsMerchantCategoryRestrictionsFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateIssuingControlsMerchantCategoryRestrictions,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateIssuingControlsMerchantCategoryRestrictions$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateIssuingControlsMerchantCategoryRestrictions' from JSON`,
  );
}

/** @internal */
export const UpdateIssuingControlsMerchantRestrictions$inboundSchema: z.ZodType<
  UpdateIssuingControlsMerchantRestrictions,
  z.ZodTypeDef,
  unknown
> = z.object({
  mode: types.optional(IssuingControlsRestrictionMode$inboundSchema),
  merchants: types.optional(z.array(MerchantEntry$inboundSchema)),
});
/** @internal */
export type UpdateIssuingControlsMerchantRestrictions$Outbound = {
  mode?: string | undefined;
  merchants?: Array<MerchantEntry$Outbound> | undefined;
};

/** @internal */
export const UpdateIssuingControlsMerchantRestrictions$outboundSchema:
  z.ZodType<
    UpdateIssuingControlsMerchantRestrictions$Outbound,
    z.ZodTypeDef,
    UpdateIssuingControlsMerchantRestrictions
  > = z.object({
    mode: IssuingControlsRestrictionMode$outboundSchema.optional(),
    merchants: z.array(MerchantEntry$outboundSchema).optional(),
  });

export function updateIssuingControlsMerchantRestrictionsToJSON(
  updateIssuingControlsMerchantRestrictions:
    UpdateIssuingControlsMerchantRestrictions,
): string {
  return JSON.stringify(
    UpdateIssuingControlsMerchantRestrictions$outboundSchema.parse(
      updateIssuingControlsMerchantRestrictions,
    ),
  );
}
export function updateIssuingControlsMerchantRestrictionsFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateIssuingControlsMerchantRestrictions,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateIssuingControlsMerchantRestrictions$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateIssuingControlsMerchantRestrictions' from JSON`,
  );
}

/** @internal */
export const UpdateIssuingControlsAllowedSchedule$inboundSchema: z.ZodType<
  UpdateIssuingControlsAllowedSchedule,
  z.ZodTypeDef,
  unknown
> = z.object({
  timezone: types.optional(types.string()),
  windows: types.optional(z.array(ScheduleWindow$inboundSchema)),
});
/** @internal */
export type UpdateIssuingControlsAllowedSchedule$Outbound = {
  timezone?: string | undefined;
  windows?: Array<ScheduleWindow$Outbound> | undefined;
};

/** @internal */
export const UpdateIssuingControlsAllowedSchedule$outboundSchema: z.ZodType<
  UpdateIssuingControlsAllowedSchedule$Outbound,
  z.ZodTypeDef,
  UpdateIssuingControlsAllowedSchedule
> = z.object({
  timezone: z.string().optional(),
  windows: z.array(ScheduleWindow$outboundSchema).optional(),
});

export function updateIssuingControlsAllowedScheduleToJSON(
  updateIssuingControlsAllowedSchedule: UpdateIssuingControlsAllowedSchedule,
): string {
  return JSON.stringify(
    UpdateIssuingControlsAllowedSchedule$outboundSchema.parse(
      updateIssuingControlsAllowedSchedule,
    ),
  );
}
export function updateIssuingControlsAllowedScheduleFromJSON(
  jsonString: string,
): SafeParseResult<UpdateIssuingControlsAllowedSchedule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateIssuingControlsAllowedSchedule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateIssuingControlsAllowedSchedule' from JSON`,
  );
}

/** @internal */
export const UpdateIssuingControls$inboundSchema: z.ZodType<
  UpdateIssuingControls,
  z.ZodTypeDef,
  unknown
> = z.object({
  velocityLimits: types.optional(z.array(IssuingVelocityLimit$inboundSchema)),
  merchantCategoryRestrictions: z.nullable(
    z.lazy(() =>
      UpdateIssuingControlsMerchantCategoryRestrictions$inboundSchema
    ),
  ).optional(),
  merchantRestrictions: z.nullable(
    z.lazy(() => UpdateIssuingControlsMerchantRestrictions$inboundSchema),
  ).optional(),
  allowedSchedule: z.nullable(
    z.lazy(() => UpdateIssuingControlsAllowedSchedule$inboundSchema),
  ).optional(),
  expiresOn: z.nullable(types.date()).optional(),
});
/** @internal */
export type UpdateIssuingControls$Outbound = {
  velocityLimits?: Array<IssuingVelocityLimit$Outbound> | undefined;
  merchantCategoryRestrictions?:
    | UpdateIssuingControlsMerchantCategoryRestrictions$Outbound
    | null
    | undefined;
  merchantRestrictions?:
    | UpdateIssuingControlsMerchantRestrictions$Outbound
    | null
    | undefined;
  allowedSchedule?:
    | UpdateIssuingControlsAllowedSchedule$Outbound
    | null
    | undefined;
  expiresOn?: string | null | undefined;
};

/** @internal */
export const UpdateIssuingControls$outboundSchema: z.ZodType<
  UpdateIssuingControls$Outbound,
  z.ZodTypeDef,
  UpdateIssuingControls
> = z.object({
  velocityLimits: z.array(IssuingVelocityLimit$outboundSchema).optional(),
  merchantCategoryRestrictions: z.nullable(
    z.lazy(() =>
      UpdateIssuingControlsMerchantCategoryRestrictions$outboundSchema
    ),
  ).optional(),
  merchantRestrictions: z.nullable(
    z.lazy(() => UpdateIssuingControlsMerchantRestrictions$outboundSchema),
  ).optional(),
  allowedSchedule: z.nullable(
    z.lazy(() => UpdateIssuingControlsAllowedSchedule$outboundSchema),
  ).optional(),
  expiresOn: z.nullable(z.date().transform(v => v.toISOString())).optional(),
});

export function updateIssuingControlsToJSON(
  updateIssuingControls: UpdateIssuingControls,
): string {
  return JSON.stringify(
    UpdateIssuingControls$outboundSchema.parse(updateIssuingControls),
  );
}
export function updateIssuingControlsFromJSON(
  jsonString: string,
): SafeParseResult<UpdateIssuingControls, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateIssuingControls$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateIssuingControls' from JSON`,
  );
}
