/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type WebhookBillingStatementCreated = {
  statementID: string;
};

/** @internal */
export const WebhookBillingStatementCreated$inboundSchema: z.ZodType<
  WebhookBillingStatementCreated,
  z.ZodTypeDef,
  unknown
> = z.object({
  statementID: z.string(),
});

/** @internal */
export type WebhookBillingStatementCreated$Outbound = {
  statementID: string;
};

/** @internal */
export const WebhookBillingStatementCreated$outboundSchema: z.ZodType<
  WebhookBillingStatementCreated$Outbound,
  z.ZodTypeDef,
  WebhookBillingStatementCreated
> = z.object({
  statementID: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WebhookBillingStatementCreated$ {
  /** @deprecated use `WebhookBillingStatementCreated$inboundSchema` instead. */
  export const inboundSchema = WebhookBillingStatementCreated$inboundSchema;
  /** @deprecated use `WebhookBillingStatementCreated$outboundSchema` instead. */
  export const outboundSchema = WebhookBillingStatementCreated$outboundSchema;
  /** @deprecated use `WebhookBillingStatementCreated$Outbound` instead. */
  export type Outbound = WebhookBillingStatementCreated$Outbound;
}

export function webhookBillingStatementCreatedToJSON(
  webhookBillingStatementCreated: WebhookBillingStatementCreated,
): string {
  return JSON.stringify(
    WebhookBillingStatementCreated$outboundSchema.parse(
      webhookBillingStatementCreated,
    ),
  );
}

export function webhookBillingStatementCreatedFromJSON(
  jsonString: string,
): SafeParseResult<WebhookBillingStatementCreated, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookBillingStatementCreated$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookBillingStatementCreated' from JSON`,
  );
}
